import AddictedToTheMachine from '../../assets/images/AddictedToTheMachine.jpg'

export default {
  id: 7,
  title: 'AddictedToTheMachine',
  img: AddictedToTheMachine,
  songs: [
    { songTitle: 'Addicted to the Machine', mp3Path: null },
    { songTitle: 'Fool That You Are', mp3Path: null },
    { songTitle: "Kate's Gone", mp3Path: null },
    { songTitle: 'This Is What You Are', mp3Path: null },
    { songTitle: 'The Taken', mp3Path: null },
    { songTitle: 'Get Up and Do It Again', mp3Path: null },
    { songTitle: 'The Angel By My Side', mp3Path: null },
    { songTitle: 'World of the Morro', mp3Path: null },
    { songTitle: "I'm Here For You", mp3Path: null },
    { songTitle: 'Escape', mp3Path: null },
    { songTitle: 'Gift of Charity', mp3Path: null },
    { songTitle: 'She Makes Me Complete', mp3Path: null },
    { songTitle: 'Doomsday Prophet', mp3Path: null },
    { songTitle: 'As the Rest of Us Get Used', mp3Path: null },
    { songTitle: 'Tonight Believe', mp3Path: null },
    { songTitle: "Time Won't Keep", mp3Path: null },
    { songTitle: 'To Know', mp3Path: null },
    { songTitle: 'The Strength of My Life', mp3Path: null },
    { songTitle: 'Here We Go', mp3Path: null },
    { songTitle: 'Round the Round', mp3Path: null },
    { songTitle: 'Maybe This Time', mp3Path: null },
    { songTitle: 'I Come Looking for You', mp3Path: null },
    { songTitle: 'Eva', mp3Path: null },
    { songTitle: 'Something Must Be Wrong', mp3Path: null },
    { songTitle: 'Pink Boots, Green Laces', mp3Path: null },
    { songTitle: 'I Love Coming Home to You', mp3Path: null },
    { songTitle: "Ain't These Them Hard Times", mp3Path: null },
  ],
};
