import DejandoLaGalaxia from '../../assets/images/DejandoLaGalaxia.jpg'

export default {
  id: 9,
  title: 'Dejando La Galaxia',
  img: DejandoLaGalaxia,
  songs: [
    { songTitle: 'Escape Velocity', mp3Path: null },
    { songTitle: 'Navigating the EMC-2X2 Wormhole', mp3Path: null },
    { songTitle: 'Arpeg-Gi-Oh', mp3Path: null },
    { songTitle: 'Spacecraft on Cruise Control', mp3Path: null },
    { songTitle: 'Vintage Motion 80', mp3Path: null },
    { songTitle: 'When I Return to You', mp3Path: null },
    { songTitle: 'Riding the Solar Winds to Triton', mp3Path: null },
    { songTitle: 'On the Other Side of the Universe', mp3Path: null },
    { songTitle: 'Kelvin to Go', mp3Path: null },
    { songTitle: 'Life on Other Worlds', mp3Path: null },
    { songTitle: 'Star Jump To,...', mp3Path: null },
    { songTitle: "As Long as You're Here With Me", mp3Path: null },
    { songTitle: 'Creeping In the Dark', mp3Path: null },
    { songTitle: 'Checkered Cab to Pluto', mp3Path: null },
    { songTitle: 'Now Passing Vega', mp3Path: null },
    { songTitle: 'Pulse', mp3Path: null },
    { songTitle: 'Adrift in Space', mp3Path: null },
    { songTitle: 'Round the Round', mp3Path: null },
    { songTitle: "The Eleven Mines of Eden's Second Moon", mp3Path: null },
    { songTitle: 'Curse of the Heretic', mp3Path: null },
    { songTitle: 'Just a Few More Light Years Away', mp3Path: null },
    { songTitle: 'Holywood Heavens', mp3Path: null },
    { songTitle: '7.83 - Planet Vibes', mp3Path: null },
    { songTitle: 'Leaving the Galaxy', mp3Path: null },
  ],
};
