import Cover from '../../assets/images/45a - The Fundamental Lord Baldwin.jpg';

export default {
  id: 'ba8b99b5-932c-4d8c-9fd1-91201f3d89c9',
  title: 'The Fundamental Lord Baldwin',
  img: Cover,
  songs: [
    { songTitle: "Lonely Too Long (From, LONELY TOO LONG)" },
    { songTitle: "So Close And Yet So Far (From, LONELY TOO LONG)" },
    { songTitle: "A Working Man (From, A WORKING MAN)" },
    { songTitle: "In The Heart Of The Family (From, A WORKING MAN)" },
    { songTitle: "Two Dollars Short (From, IT WASN'T MY FAULT)" },
    { songTitle: "Crazy Cars (From, IT WASN'T MY FAULT)" },
    { songTitle: "On The Open Range (From, ON THE OPEN RANGE)" },
    { songTitle: "Stealing Away (From, ON THE OPEN RANGE)" },
    { songTitle: "One Day At A Time (From, TAKING ME FOR A RIDE)" },
    { songTitle: "Don't Make Me Beg For Your Love (From, TAKING ME FOR A RIDE)" },
    { songTitle: "Ever On (From, EVER ON)" },
    { songTitle: "Sitting Here On This Couch (From, EVER ON)" },
    { songTitle: "A Hole In The Sky (From, EVER ON)" },
    { songTitle: "Spinning My Wheels (From, SPINNING MY WHEELS)" },
    { songTitle: "Blue With A Broken Heart (From, SPINNING MY WHEELS)" },
    { songTitle: "Back In The Navy Again (From, HEAVEN)" },
    { songTitle: "You've Got To Believe (From, YOU'VE GOT TO BELIEVE)" },
    { songTitle: "When You Touch My Heart (From, YOU'VE GOT TO BELIEVE)" },
    { songTitle: "A Family Man (From, A FAMILY MAN)" },
    { songTitle: "Harmonica Foot Stomp (From, A FAMILY MAN)" },
    { songTitle: "Just Another Bimmy (From, TAKING ME FOR A RIDE)" },
  ],
};
